package com.colleagues.austrom.models

import android.content.Context
import com.colleagues.austrom.R

class Currency(val code: String = "",
               var name : String = "",
               var symbol : String ="",
               var exchangeRate : Double = 0.0) {

    companion object{
        fun switchRatesToNewBaseCurrency(currenciesList: MutableMap<String, Currency>, newBaseCurrencyCode: String?) : MutableMap<String, Currency> {
            val newBaseCurrency = currenciesList[newBaseCurrencyCode]
            if (newBaseCurrency!=null) {
                val denominator = newBaseCurrency.exchangeRate
                for (currency in currenciesList) {
                    currency.value.exchangeRate /= denominator
                }
            }
            return currenciesList
        }

        fun localizeCurrencyNames(currenciesList: MutableMap<String, Currency>, context: Context) : MutableMap<String, Currency> {
            for (currency in currenciesList) {
                if (currenciesNamesResourcesMap.containsKey(currency.key)){
                    currency.value.name = context.getString(currenciesNamesResourcesMap[currency.key]!!)
                }
            }
            return currenciesList
        }

        private val currenciesNamesResourcesMap: Map<String, Int> = mapOf(
            Pair("ADA", R.string.ADA),
            Pair("AED", R.string.AED),
            Pair("AFN", R.string.AFN),
            Pair("ALL", R.string.ALL),
            Pair("AMD", R.string.AMD),
            Pair("ANG", R.string.ANG),
            Pair("AOA", R.string.AOA),
            Pair("ARB", R.string.ARB),
            Pair("ARS", R.string.ARS),
            Pair("AUD", R.string.AUD),
            Pair("AVAX", R.string.AVAX),
            Pair("AWG", R.string.AWG),
            Pair("AZN", R.string.AZN),
            Pair("BAM", R.string.BAM),
            Pair("BBD", R.string.BBD),
            Pair("BDT", R.string.BDT),
            Pair("BGN", R.string.BGN),
            Pair("BHD", R.string.BHD),
            Pair("BIF", R.string.BIF),
            Pair("BMD", R.string.BMD),
            Pair("BNB", R.string.BNB),
            Pair("BND", R.string.BND),
            Pair("BOB", R.string.BOB),
            Pair("BRL", R.string.BRL),
            Pair("BSD", R.string.BSD),
            Pair("BTC", R.string.BTC),
            Pair("BTN", R.string.BTN),
            Pair("BWP", R.string.BWP),
            Pair("BYN", R.string.BYN),
            Pair("BYR", R.string.BYR),
            Pair("BZD", R.string.BZD),
            Pair("CAD", R.string.CAD),
            Pair("CDF", R.string.CDF),
            Pair("CHF", R.string.CHF),
            Pair("CLF", R.string.CLF),
            Pair("CLP", R.string.CLP),
            Pair("CNY", R.string.CNY),
            Pair("COP", R.string.COP),
            Pair("CRC", R.string.CRC),
            Pair("CUC", R.string.CUC),
            Pair("CUP", R.string.CUP),
            Pair("CVE", R.string.CVE),
            Pair("CZK", R.string.CZK),
            Pair("DAI", R.string.DAI),
            Pair("DJF", R.string.DJF),
            Pair("DKK", R.string.DKK),
            Pair("DOP", R.string.DOP),
            Pair("DOT", R.string.DOT),
            Pair("DZD", R.string.DZD),
            Pair("EGP", R.string.EGP),
            Pair("ERN", R.string.ERN),
            Pair("ETB", R.string.ETB),
            Pair("ETH", R.string.ETH),
            Pair("EUR", R.string.EUR),
            Pair("FJD", R.string.FJD),
            Pair("FKP", R.string.FKP),
            Pair("GBP", R.string.GBP),
            Pair("GEL", R.string.GEL),
            Pair("GGP", R.string.GGP),
            Pair("GHS", R.string.GHS),
            Pair("GIP", R.string.GIP),
            Pair("GMD", R.string.GMD),
            Pair("GNF", R.string.GNF),
            Pair("GTQ", R.string.GTQ),
            Pair("GYD", R.string.GYD),
            Pair("HKD", R.string.HKD),
            Pair("HNL", R.string.HNL),
            Pair("HRK", R.string.HRK),
            Pair("HTG", R.string.HTG),
            Pair("HUF", R.string.HUF),
            Pair("IDR", R.string.IDR),
            Pair("ILS", R.string.ILS),
            Pair("IMP", R.string.IMP),
            Pair("INR", R.string.INR),
            Pair("IQD", R.string.IQD),
            Pair("IRR", R.string.IRR),
            Pair("ISK", R.string.ISK),
            Pair("JEP", R.string.JEP),
            Pair("JMD", R.string.JMD),
            Pair("JOD", R.string.JOD),
            Pair("JPY", R.string.JPY),
            Pair("KES", R.string.KES),
            Pair("KGS", R.string.KGS),
            Pair("KHR", R.string.KHR),
            Pair("KMF", R.string.KMF),
            Pair("KPW", R.string.KPW),
            Pair("KRW", R.string.KRW),
            Pair("KWD", R.string.KWD),
            Pair("KYD", R.string.KYD),
            Pair("KZT", R.string.KZT),
            Pair("LAK", R.string.LAK),
            Pair("LBP", R.string.LBP),
            Pair("LKR", R.string.LKR),
            Pair("LRD", R.string.LRD),
            Pair("LSL", R.string.LSL),
            Pair("LTC", R.string.LTC),
            Pair("LTL", R.string.LTL),
            Pair("LVL", R.string.LVL),
            Pair("LYD", R.string.LYD),
            Pair("MAD", R.string.MAD),
            Pair("MATIC", R.string.MATIC),
            Pair("MDL", R.string.MDL),
            Pair("MGA", R.string.MGA),
            Pair("MKD", R.string.MKD),
            Pair("MMK", R.string.MMK),
            Pair("MNT", R.string.MNT),
            Pair("MOP", R.string.MOP),
            Pair("MRO", R.string.MRO),
            Pair("MRU", R.string.MRU),
            Pair("MUR", R.string.MUR),
            Pair("MVR", R.string.MVR),
            Pair("MWK", R.string.MWK),
            Pair("MXN", R.string.MXN),
            Pair("MYR", R.string.MYR),
            Pair("MZN", R.string.MZN),
            Pair("NAD", R.string.NAD),
            Pair("NGN", R.string.NGN),
            Pair("NIO", R.string.NIO),
            Pair("NOK", R.string.NOK),
            Pair("NPR", R.string.NPR),
            Pair("NZD", R.string.NZD),
            Pair("OMR", R.string.OMR),
            Pair("OP", R.string.OP),
            Pair("PAB", R.string.PAB),
            Pair("PEN", R.string.PEN),
            Pair("PGK", R.string.PGK),
            Pair("PHP", R.string.PHP),
            Pair("PKR", R.string.PKR),
            Pair("PLN", R.string.PLN),
            Pair("PYG", R.string.PYG),
            Pair("QAR", R.string.QAR),
            Pair("RON", R.string.RON),
            Pair("RSD", R.string.RSD),
            Pair("RUB", R.string.RUB),
            Pair("RWF", R.string.RWF),
            Pair("SAR", R.string.SAR),
            Pair("SBD", R.string.SBD),
            Pair("SCR", R.string.SCR),
            Pair("SDG", R.string.SDG),
            Pair("SEK", R.string.SEK),
            Pair("SGD", R.string.SGD),
            Pair("SHP", R.string.SHP),
            Pair("SLL", R.string.SLL),
            Pair("SOL", R.string.SOL),
            Pair("SOS", R.string.SOS),
            Pair("SRD", R.string.SRD),
            Pair("STD", R.string.STD),
            Pair("STN", R.string.STN),
            Pair("SVC", R.string.SVC),
            Pair("SYP", R.string.SYP),
            Pair("SZL", R.string.SZL),
            Pair("THB", R.string.THB),
            Pair("TJS", R.string.TJS),
            Pair("TMT", R.string.TMT),
            Pair("TND", R.string.TND),
            Pair("TOP", R.string.TOP),
            Pair("TRY", R.string.TRY),
            Pair("TTD", R.string.TTD),
            Pair("TWD", R.string.TWD),
            Pair("TZS", R.string.TZS),
            Pair("UAH", R.string.UAH),
            Pair("UGX", R.string.UGX),
            Pair("USD", R.string.USD),
            Pair("USDC", R.string.USDC),
            Pair("USDT", R.string.USDT),
            Pair("UYU", R.string.UYU),
            Pair("UZS", R.string.UZS),
            Pair("VEF", R.string.VEF),
            Pair("VES", R.string.VES),
            Pair("VND", R.string.VND),
            Pair("VUV", R.string.VUV),
            Pair("WST", R.string.WST),
            Pair("XAF", R.string.XAF),
            Pair("XAG", R.string.XAG),
            Pair("XAU", R.string.XAU),
            Pair("XCD", R.string.XCD),
            Pair("XDR", R.string.XDR),
            Pair("XOF", R.string.XOF),
            Pair("XPD", R.string.XPD),
            Pair("XPF", R.string.XPF),
            Pair("XPT", R.string.XPT),
            Pair("XRP", R.string.XRP),
            Pair("YER", R.string.YER),
            Pair("ZAR", R.string.ZAR),
            Pair("ZMK", R.string.ZMK),
            Pair("ZMW", R.string.ZMW),
            Pair("ZWL", R.string.ZWL),
        )
    }
}